version: '2.2'
services:

  web:
    build:
      context: ../dockerfiles/web_prd
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: "kinoue.tk -> http://app:3000"
      STAGE: 'production'
      WORKER_PROCESSES: 'auto'
      WEBSOCKET: 'true'
    logging:
      driver: "journald"
    restart: always

  app:
    build:
      context: ../dockerfiles/app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    volumes:
      - ../../../src:/opt/myapp/src
      - node_modules:/opt/myapp/src/node/node_modules
      - vue_modules:/opt/myapp/src/vue/node_modules
    init: true
    command:
      /bin/sh -c
      "  npm install        --prefix /opt/myapp/src/vue
      && npm install        --prefix /opt/myapp/src/vue --only=dev
      && npm install        --prefix /opt/myapp/src/node
      && npm run production --prefix /opt/myapp/src/vue
      && npm run start      --prefix /opt/myapp/src/node"
    logging:
      driver: "journald"
    restart: always

volumes:
  node_modules:
    driver: 'local'
  vue_modules:
    driver: 'local'