version: '2.2'
services:

  web:
    build:
      context: ../dockerfiles/web_prd
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../../../src/vue/dist:/opt/myapp/src/vue/dist
      - ../dockerfiles/web_prd/myapp.conf:/var/lib/nginx-conf/kinoue.tk.ssl.conf.erb:ro
    environment:
      DOMAINS: "kinoue.tk -> http://app"
      STAGE: 'production'
      WORKER_PROCESSES: 'auto'
      WEBSOCKET: 'true'
    logging:
      driver: "journald"
    restart: always

  app:
    build:
      context: ../dockerfiles/app
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ../../../src:/opt/myapp/src
    init: true
    command:
      /bin/sh -c
      "  npm install        --prefix /opt/myapp/src/vue
      && npm install        --prefix /opt/myapp/src/node
      && npm run production --prefix /opt/myapp/src/vue
      && npm run start      --prefix /opt/myapp/src/node"
    logging:
      driver: "journald"
    restart: always

